name: Melee
main: me.cxom.melee2.Melee
version: 0.10.3vRabbit-Refactor-0.11.2
api-version: 1.19
author: Cxom
description: Rendition 2 of The Minecraft minigame Melee
depend: [PunchTree-Minigames, MovementPlusPlus]

commands:
    melee:
        usage: /melee [leave|join <game>]
        description: For the Melee minigame.
    rabbit:
        usage: /rabbit [leave|join <game>]
        description: For the Rabbit minigame.
    games:

permissions:
    melee.admin:
        default: false