name: Melee
main: me.cxom.melee2.Melee
version: 0.9
description: Rendition 2 of the Minecraft minigame Melee
depend: [MovementPlusPlus]

commands:
    melee:
        usage: /melee [leave|join <game>]
        description: For the Melee minigame.