name: Melee
main: me.cxom.melee2.Melee
version: 0.10.3vRabbit-Refactor-0.6
api-version: 1.16
author: Cxom
description: Rendition 2 of The Minecraft minigame Melee
depend: [PunchTree-Minigames, MovementPlusPlus]

commands:
    melee:
        usage: /melee [leave|join <game>]
        description: For the Melee minigame.
    rabbit:
        usage: /rabbit [leave|join <game>]
        description: For the Rabbit minigame.
    games:
        aliases: [join]